# Generated by Django 4.1.7 on 2023-09-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='marks',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
